#!/bin/sh

set -e
test $DEBIAN_SCRIPT_DEBUG && set -v -x

# use debconf
. /usr/share/debconf/confmodule

if [ -x "/etc/init.d/glbd" ]; then
	if [ -x /usr/sbin/invoke-rc.d ]; then
	   invoke-rc.d glbd restart
	else
	   /etc/init.d/glbd restart
	fi
fi

db_stop

#DEBHELPER#

exit 0
# vim:set ai et sts=2 sw=2 tw=0:
